name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify files exist
        run: |
          test -f insert_books.js || (echo "insert_books.js not found" && exit 1)
          test -f queries.js || (echo "queries.js not found" && exit 1)

      - name: Install dependencies
        run: npm install

      - name: Run insert_books.js
        run: node insert_books.js

      - name: Run queries.js
        run: node queries.js
